### ISSUE TITLE
1.19.x / 1.20.x

### ISSUE THREAD

**Issue by Faboslav** [MastroCaleb/Little-Ants#10]
Hello there, any plans of porting this mod to 1.19x/1.20.x or continuing development?

**Comment by MastroCaleb** [comment]
i am thinking about continuing development and updating to newer versions of minecraft, but i'll probably wait until the last 1.20.X update is announced to do a 1.19.4 and 1.20.x version

**Comment by Faboslav** [comment]
Bump, if wanted we can do some kind of collaboration (i can setup a modloader project so it works for all platforms and port it and/or maintain it) if wanted, let me know for sure :).

**Comment by MastroCaleb** [comment]
Well i honestly wouldn't mind. I have been pretty bummed out these months so i have been slacking off. 

So yeah, sure! I really love this mod but i can't bring myself to update it. Let me know what i can do to help, like give you the permits and all!

**Comment by Faboslav** [comment]
Do you have the discord?

**Comment by MastroCaleb** [comment]
Yes, send me a friend request, the nick is (I am in the Fabric Server if you dont find me): mastrocaleb
