### ISSUE TITLE
Right Clicking or Holding Bonemeal continuously consumes items

### ISSUE THREAD

**Issue by DaFuqs** [MastroCaleb/Little-Ants#8]
Running Little Ants in a biggish pack I noticed some weird behavior with Bonemeal and could drill it down to Little Ants:

Having a stack of 64 bonemeal in hand and targetting any block like grass rapidly consumes 2 Bonemeal in a single tick. Keeping the Key held consumes more bonemeal every half a second or so, even when there is nothing there it could be used on.

The Culprit: [Bonemeal Item Mixin ](https://github.com/MastroCaleb/Little-Ants/blame/d2c3c556de86d6bd1b30a1d36551c22c83de5f53/src/main/java/toxican/caleb/ants/mixin/AntsMixin.java#L18)

**Comment by MastroCaleb** [comment]
ehy, sorry for not responding, im working on a fix right now as recently was found a critical bug that deleted ants from nests. in a few hours i'll release a fix. thanks for the report

**Comment by MastroCaleb** [comment]
Hi, the issue has now been fixed, i'll release an update later tomorrow after some more debugging. Thanks again for the report!
