### ISSUE TITLE
[13:38:57] [Server thread/WARN]: Tried to load a block entity for block Block{ants:dirt_ant_nest}[clay_level=0,facing=south] but failed at location class_2338{x=-476, y=107, z=541} [13:38:57] [Server thread/ERROR]: Failed to load data for block entity ants:nest java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by inikishev** [MastroCaleb/Little-Ants#9]
https://gist.github.com/stunlocked1/9484b9b0282870ff30c7285b56052714

**Comment by MastroCaleb** [comment]
Hi, I’ve recently encountered the same issue, im working on a fix right now and im really sorry for the inconvenience, once i find a fix I’ll instantly update the mod

**Comment by MastroCaleb** [comment]
Hi, here with an update: I fixed the bug, a version is releasing later today after some more debugging. Thank you for reporting.
